// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var masses = Utils.readFileIntoList("Day1Input");

function calcFuel(mass) {
  return Js_math.floor(mass / 3) - 2 | 0;
}

var totalFuel = Belt_List.reduce(Belt_List.map(masses, (function (mass) {
            return calcFuel(Caml_format.caml_float_of_string(mass.trim()));
          })), 0, (function (acc, next) {
        return acc + next | 0;
      }));

console.log(totalFuel);

exports.masses = masses;
exports.calcFuel = calcFuel;
exports.totalFuel = totalFuel;
/* masses Not a pure module */
