// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var EasyTree = require("easy-tree");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var Tree = { };

function parseLineToMap(line) {
  var map = { };
  var orbital = line.split(")");
  if (orbital.length === 2) {
    var match = Belt_Array.get(orbital, 0);
    if (match !== undefined) {
      map[match] = Belt_Array.get(orbital, 1);
    }
    
  }
  return map;
}

function countDirectAndIndirectOrbits(input) {
  var orbitalLines = Utils.multiLineToList(input);
  var orbitalMaps = Belt_List.toArray(Belt_List.map(orbitalLines, parseLineToMap));
  var tree = new EasyTree(orbitalMaps);
  tree.walk((function (node) {
          console.log(node);
          return /* () */0;
        }));
  return /* () */0;
}

var testCase = "\n    COM)B\n    B)C\n    C)D\n    D)E\n    E)F\n    B)G\n    G)H\n    D)I\n    E)J\n    J)K\n    K)L\n";

exports.Tree = Tree;
exports.testCase = testCase;
exports.parseLineToMap = parseLineToMap;
exports.countDirectAndIndirectOrbits = countDirectAndIndirectOrbits;
/* Utils Not a pure module */
