// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function multiLineToList(str) {
  return Belt_List.map(Belt_List.fromArray(str.trim().split("\n")), (function (str) {
                return str.trim();
              }));
}

function readFileIntoList(filename) {
  return multiLineToList(Fs.readFileSync("./src/" + (filename + ".txt"), "utf8"));
}

exports.multiLineToList = multiLineToList;
exports.readFileIntoList = readFileIntoList;
/* fs Not a pure module */
