// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function readFileIntoList(filename) {
  var file = Fs.readFileSync("./src/" + (filename + ".txt"), "utf8");
  return Belt_List.fromArray(file.split("\n"));
}

exports.readFileIntoList = readFileIntoList;
/* fs Not a pure module */
